### ISSUE TITLE
Update submit file for CentOS7

### ISSUE THREAD

**Issue by SteveGoldstein** [megarcia/HTCondor_examples#2]
The README file has been updated:

but the submit files haven't:

`[sgoldstein@submit2 HTCondor_examples]$ grep OpSys csv_processing/*sub
requirements = (OpSys == "LINUX") && (OpSysMajorVer == 6)
[sgoldstein@submit2 HTCondor_examples]$ 
[sgoldstein@submit2 HTCondor_examples]$ 
[sgoldstein@submit2 HTCondor_examples]$ 
[sgoldstein@submit2 HTCondor_examples]$ 
[sgoldstein@submit2 HTCondor_examples]$ grep OpSys image_processing/*sub

image_processing/calc_L57_chunk_vi.sub:requirements = (OpSys == "LINUX") && (OpSysMajorVer == 6)

image_processing/chunk_L57_bands.sub:requirements = (OpSys == "LINUX") && (OpSysMajorVer == 6)

image_processing/diff_vi.sub:requirements = (OpSys == "LINUX") && (OpSysMajorVer == 6)

image_processing/stitch_vi.sub:requirements = (OpSys == "LINUX") && (OpSysMajorVer == 6)
`

**Comment by megarcia** [comment]
Thanks, Steve--I will update those.
